#%RAML 1.0 DataType
type: object
properties:
  header:
    type: string
    description: short description of the error
    example: "Something went wrong."
  code:
    type: string
    description: response code
  message:
    type: string
    description: additional description/remarks